{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "water-timeseries.fullname" $ }}-{{ .name }}
  labels:
    {{- include "water-timeseries.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  selector:
    {{- include "water-timeseries.selectorLabels" $ | nindent 4 }}
  ports:
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
{{- end }}
