apiVersion: v2
name: water-timeseries
description: Helm chart for the Water Timeseries Streamlit dashboard
sources:
  - https://github.com/PermafrostDiscoveryGateway/water-timeseries-v2
type: application
version: 0.9.4
appVersion: "0.9.4"
